theme = dark:Catppuccin Macchiato,light:Catppuccin Latte
font-family = "GeistMono Nerd Font"
font-size = 13
font-feature = calt, liga, dlig
cursor-style = bar

window-padding-x = 8
window-padding-y = 8
window-height = 33
window-width = 118
confirm-close-surface = false
cursor-click-to-move = true
unfocused-split-opacity = 0.8

shell-integration = detect
shell-integration-features = ssh-env

keybind = alt+left=text:\x1bb
keybind = alt+right=text:\x1bf
keybind = super+left=text:\x01
keybind = super+right=text:\x05
keybind = super+t=new_tab
keybind = super+k=text:\x0c
keybind = super+shift+r=text:reload\x0d
keybind = super+shift+g=text:git\x20status\x0d
keybind = super+shift+l=text:ll\x0d
keybind = super+f=text:/
keybind = super+shift+f=text:?
